services:
  ubuntu:
    container_name: workstation_${COMPOSE_PROJECT_NAME}
    image: mcr.microsoft.com/devcontainers/base:ubuntu-${UBUNTU_VERSION}
    restart: "unless-stopped"
    tty: true
    stop_signal: SIGTERM
    volumes:
      - ./:/${WORKSPACE_FOLDER}
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials
    networks:
      - moztopia_network

networks:
  moztopia_network:
    name: moztopia_network
    driver: bridge
